### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by EuskalPoxo** [KitronikLtd/micropython-microbit-kitronik-text32#1]
The code does not work on my micro: bit (I am using a micro: bit v2). I have tried an example with MakeCode to rule out that it was a hardware problem, and in that way it works fine.

**Comment by DaveAtKitronik** [comment]
@EuskalPoxo could you provide any more info? What have you tried?
@PhilAtKitronik

**Comment by EuskalPoxo** [comment]
Exactly the example in file 'VIEW_TEXT32.py'. I send some pictures whith de screens after press buttons A and B, 
although every time you restart it does a different thing. Also, take a long time. In MakeCode 
![Step_1](https://user-images.githubusercontent.com/75129078/108837169-2b010080-75d2-11eb-8b53-edcc84a80e8a.jpg)
![Step_2](https://user-images.githubusercontent.com/75129078/108837172-2c322d80-75d2-11eb-9998-4f698e9b75dd.jpg)
![Step_3](https://user-images.githubusercontent.com/75129078/108837175-2d635a80-75d2-11eb-92ba-8e89b4f38de7.jpg)
![Step_4](https://user-images.githubusercontent.com/75129078/108837178-2dfbf100-75d2-11eb-80c3-c3fec0d4458a.jpg)



it works perfect.

**Comment by PhilAtKitronik** [comment]
Currently remote working,  I will have to wait a day or so to get a VIEW Text sent to me then can look into the code.  Thank you for your patience while I get this resolved for you

**Comment by EuskalPoxo** [comment]
> Currently remote working, I will have to wait a day or so to get a VIEW Text sent to me then can look into the code. Thank you for your patience while I get this resolved for you

**Comment by EuskalPoxo** [comment]
Thank you very much for your interest.

I just did the test on a micro: bit V1 (first version) and it works perfectly, so the problem seems to occur because of the micro: bit V2. Maybe something has changed in SPI protocol for this version? I don't know.

Thank you very much for your help, my friend.

**Comment by PhilAtKitronik** [comment]
Hi EuskalPoxo,
Can i ask what editor you are using as well please?

> Thank you very much for your interest.
> 
> I just did the test on a micro: bit V1 (first version) and it works perfectly, so the problem seems to occur because of the micro: bit V2. Maybe something has changed in SPI protocol for this version? I don't know.
> 
> Thank you very much for your help, my friend.

**Comment by EuskalPoxo** [comment]
> Hi EuskalPoxo,
> Can i ask what editor you are using as well please?
> 
> > Thank you very much for your interest.
> > I just did the test on a micro: bit V1 (first version) and it works perfectly, so the problem seems to occur because of the micro: bit V2. Maybe something has changed in SPI protocol for this version? I don't know.
> > Thank you very much for your help, my friend.

Mu.

**Comment by EuskalPoxo** [comment]
As I told you yesterday, with micro: bit V1 it works like a charm, as you can see in this video.

https://user-images.githubusercontent.com/75129078/109016158-29106d80-76b6-11eb-8fea-bebe0d59486f.mp4

**Comment by PhilAtKitronik** [comment]
@EuskalPoxo, please see the updated committed example code.  If you can see if this has worked for you.  I have tested the code with my setup.  Please give feedback if it works or more issues.

**Comment by EuskalPoxo** [comment]
OK. I have verified that it works perfectly in both versions. Thank you very much indeed for your concern and professionalism.

Regards.
